// This file is intentionally empty.
// Prisma v5 configuration is handled via prisma/schema.prisma and the .env file.
// This file was generated by Prisma v7 init and is not needed for v5.
export {};
